export const dummyAlumni = [
    {
      id: 1,
      name: 'John Doe',
      graduationYear: 2018,
      major: 'Computer Science',
      company: 'Tech Giants Inc.',
      position: 'Software Engineer',
      image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=200&q=80',
      chat:"#",
      email: 'john.doe@example.com',
      linkedin: 'https://linkedin.com/in/johndoe',
      twitter: 'https://twitter.com/johndoe',
      github: 'https://github.com/johndoe'
    },
    {
      id: 2,
      name: 'Jane Smith',
      graduationYear: 2019,
      major: 'Business Administration',
      company: 'Finance Pros LLC',
      position: 'Financial Analyst',
      image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=200&q=80',
      chat:"#",
      email: 'jane.smith@example.com',
      linkedin: 'https://linkedin.com/in/janesmith',
      twitter: 'https://twitter.com/janesmith',
      github: 'https://github.com/janesmith'
    },
    {
      id: 3,
      name: 'Mike Johnson',
      graduationYear: 2020,
      major: 'Electrical Engineering',
      company: 'Innovate Electronics',
      position: 'Hardware Engineer',
      image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=200&q=80',
      chat:"#",
      email: 'mike.johnson@example.com',
      linkedin: 'https://linkedin.com/in/mikejohnson',
      twitter: 'https://twitter.com/mikejohnson',
      github: 'https://github.com/mikejohnson'
    },
    {
        id: 4,
        name: 'Emily Parker',
        graduationYear: 2018,
        major: 'Computer Science',
        company: 'Tech Innovators',
        position: 'Software Developer',
        image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80',
        chat:"#",
        email: 'emily.parker@example.com',
        linkedin: 'https://linkedin.com/in/emilyparker',
        twitter: 'https://twitter.com/emilyparker',
        github: 'https://github.com/emilyparker'
      },
      {
        id: 5,
        name: 'Rajesh Gupta',
        graduationYear: 2017,
        major: 'Mechanical Engineering',
        company: 'Future Motors',
        position: 'Design Engineer',
        image: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80',
        chat:"#",
        email: 'rajesh.gupta@example.com',
        linkedin: 'https://linkedin.com/in/rajeshgupta',
        twitter: 'https://twitter.com/rajeshgupta',
        github: 'https://github.com/rajeshgupta'
      },
      {
        id: 6,
        name: 'Sophia Lee',
        graduationYear: 2019,
        major: 'Information Technology',
        company: 'Data Solutions Inc.',
        position: 'Data Analyst',
        image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80',
        chat:"#",
        email: 'sophia.lee@example.com',
        linkedin: 'https://linkedin.com/in/sophialee',
        twitter: 'https://twitter.com/sophialee',
        github: 'https://github.com/sophialee'
      },
      {
        id: 7,
        name: 'Carlos Fernandez',
        graduationYear: 2016,
        major: 'Civil Engineering',
        company: 'Urban Builders',
        position: 'Project Manager',
        image: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80',
        chat:"#",
        email: 'carlos.fernandez@example.com',
        linkedin: 'https://linkedin.com/in/carlosfernandez',
        twitter: 'https://twitter.com/carlosfernandez',
        github: 'https://github.com/carlosfernandez'
      },
      {
        id: 8,
        name: 'Fatima Khan',
        graduationYear: 2021,
        major: 'Biomedical Engineering',
        company: 'MedTech Solutions',
        position: 'Research Scientist',
        image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80',
        chat:"#",
        email: 'fatima.khan@example.com',
        linkedin: 'https://linkedin.com/in/fatimakhan',
        twitter: 'https://twitter.com/fatimakhan',
        github: 'https://github.com/fatimakhan'
      }
      
  ];
